# Generated by Django 3.2.8 on 2021-10-18 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='static/productimg')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.product')),
            ],
        ),
    ]
