# Generated by Django 3.2.8 on 2021-10-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudexample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(error_messages={'blank': 'The Geeks Field you entered is not unique.'}, max_length=20),
        ),
    ]
