# Generated by Django 3.2.8 on 2021-10-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudexample', '0002_alter_employee_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(error_messages={'blank': 'This field is required.'}, max_length=20),
        ),
    ]
