# Generated by Django 3.2.8 on 2021-12-14 10:39

import crudexample.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudexample', '0003_alter_employee_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, validators=[crudexample.models.validate_geeks_mail]),
        ),
    ]
