# Generated by Django 3.2.8 on 2021-10-21 06:50

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='images',
            field=models.ImageField(blank=True, help_text='Only image formats are accepted.', null=True, upload_to='media', validators=[upload_validator.FileTypeValidator(['image/jpeg', 'image/png'])]),
        ),
    ]
