# Generated by Django 3.2.8 on 2021-10-21 10:33

from django.db import migrations, models
import multiple_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_upload', '0002_alter_multipleimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='images',
            field=models.FileField(blank=True, help_text='Only image formats are accepted.', null=True, upload_to='media', validators=[multiple_upload.models.validate_file]),
        ),
    ]
